import "~/styles/globals.css";

import { Inter } from 'next/font/google'
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({subsets: ['latin']})

function TopNav() {
  return (
    <nav className="flex items-center justify-between w-full p-4 border-b text-xl font-semibold">
      <div>
        Gallery
      </div>
      <div>
        Sign In
      </div>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col gap-4`}>
        <TopNav />
        {children}
        </body>
    </html>
  );
}
